version: 0.2

phases:
  build:
    commands:
      - echo Entered the build phase ...
      - mvn clean package
  post_build:
    commands:
      - echo Build Complete successfully
artifacts:
  files:
    - target/gistda-cspp.jar
  discard-paths: yes