DROP DATABASE IF EXISTS gistda;
DROP USER IF EXISTS `root`@`%`;
CREATE DATABASE IF NOT EXISTS gistda CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS `root`@`%` IDENTIFIED WITH mysql_native_password BY 'gistda';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, EXECUTE, CREATE VIEW, SHOW VIEW,
    CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER ON `gistda`.* TO `root`@`%`;